// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyc2rsarKfruKbpWOhYEdxuVFop_mvwo',
    appId: '1:93841452294:web:4d95322630e99e8ad94287',
    messagingSenderId: '93841452294',
    projectId: 'spotify-redesigned',
    authDomain: 'spotify-redesigned.firebaseapp.com',
    storageBucket: 'spotify-redesigned.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIo4ZKVMZCfnVV_6LFsee8AaKFxLNa8g',
    appId: '1:93841452294:android:1fccfef0042eb0e7d94287',
    messagingSenderId: '93841452294',
    projectId: 'spotify-redesigned',
    storageBucket: 'spotify-redesigned.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkgmbXAOTAKcr7aTg0NJj8awCUvvSvko',
    appId: '1:93841452294:ios:01038a6e7e92b63bd94287',
    messagingSenderId: '93841452294',
    projectId: 'spotify-redesigned',
    storageBucket: 'spotify-redesigned.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkgmbXAOTAKcr7aTg0NJj8awCUvvSvko',
    appId: '1:93841452294:ios:01038a6e7e92b63bd94287',
    messagingSenderId: '93841452294',
    projectId: 'spotify-redesigned',
    storageBucket: 'spotify-redesigned.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTyc2rsarKfruKbpWOhYEdxuVFop_mvwo',
    appId: '1:93841452294:web:cc46a5a5afca7559d94287',
    messagingSenderId: '93841452294',
    projectId: 'spotify-redesigned',
    authDomain: 'spotify-redesigned.firebaseapp.com',
    storageBucket: 'spotify-redesigned.appspot.com',
  );
}
